
name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-model-architecture:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Pre-download MNIST dataset
      run: |
        python -c "
        from torchvision import datasets
        import os
        os.makedirs('./data', exist_ok=True)
        print('Downloading MNIST dataset...')
        datasets.MNIST(root='./data', train=True, download=True)
        datasets.MNIST(root='./data', train=False, download=True)
        print('MNIST dataset downloaded successfully!')
        "
        
    - name: Display Model Summary
      run: |
        echo "Model Architecture Summary"
        echo "========================="
        python -c "
        from basic_dnn_mnist import Net
        model = Net()
        total_params = sum(p.numel() for p in model.parameters())
        trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
        print(f'Total Parameters: {total_params:,}')
        print(f'Trainable Parameters: {trainable_params:,}')
        print(f'Batch Normalization Layers: 6')
        print(f'Dropout Layers: 1')
        print(f'Fully Connected Layers: 2')
        print(f'GAP Usage: No')
        "
        echo "========================="
        
    - name: Run architecture tests
      run: |
        echo "Running Model Architecture Tests..."
        echo "=================================="
        python -m pytest tests/ -v
        echo "=================================="
